
server:
  context-path: /account
  port: 8102
  tomcat:
    access_log_enabled: true

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  
    url: jdbc:mysql://mysql:3306/account_service?characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    minIdle: 1  
    maxActive: 20  
    initialSize: 1  
    timeBetweenEvictionRunsMillis: 3000  
    minEvictableIdleTimeMillis: 300000  
    validationQuery: SELECT 1 
    testWhileIdle: true  
    testOnBorrow: false  
    testOnReturn: false 
  jpa:
    show-sql: false
    properties:
      hibernate:
        hbm2ddl:
          auto: none
          
          
rmq:
  addresses: rabbitmq:5672
  virtualHost: test
  username: test
  password: test
  group: account-service
  
swagger:
  basePackage: com.github.user.core.web
  title: 账户管理 RESTful API
  desc: 账户管理 RESTFUL API
  serviceUrl: http://www.github.com
  version: 1.0